# Generated by Django 3.2.12 on 2022-05-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinets',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
    ]
