# Generated by Django 4.0.4 on 2022-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('adventure', 'adventure'), ('horror', 'horror'), ('action', 'action'), ('indi', 'indi'), ('shooter', 'shooter'), ('puzzle', 'puzzle')], default='action', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='product_image'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
